name = "kv-get-started"
type = "service"
main = "src/index_kv.js"
compatibility_date = "2024-01-01"
account_id = "5ea66b6b4c7c45cb908111fa3259862c"
zone_id = "cf3bba94e40a7a9012f4b0b075464317"

[[kv_namespaces]]
binding = "PROPIEDADES"
id = "5ea66b6b4c7c45cb908111fa3259862c"
preview_id = "AQUI_PEGA_PREVIEW_ID"   # ← REEMPLAZA CON ID PREVIEW

[env.production]
vars = { ADMIN_PASSWORD = "admin1203" }
