cat > wrangler.toml << 'EOF'
name = "zona-admin"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "DB"
id = "5ea66b6b4c7c45cb908111fa3259862c"
preview_id = "5ea66b6b4c7c45cb908111fa3259862c"
EOF
