// Servicios de inmuhub: contenido de /servicios y /servicios/:slug.
// role: tipo de cuenta que se sugiere al registrarse desde el servicio.

export const SERVICES = [
  {
    slug: 'publicacion-de-propiedades',
    name: 'Publicación curada de propiedades',
    eyebrow: 'Propietarios',
    role: 'propietario',
    summary: 'Su propiedad se revisa, se presenta con una ficha profesional y se compara con el valor de su zona antes de publicarse.',
    lead: 'Publicar no es subir fotos y un precio. En inmuhub cada propiedad pasa por una revisión de datos, fotografías y precio antes de aparecer, para que llegue a compradores que deciden con información.',
    includes: [
      'Revisión de datos, áreas y precio antes de publicar',
      'Ficha con lectura de valor frente al rango de su zona',
      'Enlace limpio para compartir y vista previa cuidada en WhatsApp y redes',
      'Seguimiento del estado de la publicación desde su cuenta',
      'Opción de sello «Verificada» tras revisión documental',
    ],
    forWho: ['Propietarios que venden o rentan directamente', 'Herederos y familias que necesitan orden y claridad en la venta'],
    steps: [
      ['Cree su cuenta', 'Registre sus datos de contacto. No se publican.'],
      ['Envíe la propiedad', 'Datos básicos, precio y hasta 10 fotografías.'],
      ['Revisión y publicación', 'Le compartimos la lectura de valor y publicamos cuando la ficha está lista.'],
    ],
    action: 'Publicar mi propiedad',
    actionHref: '/publicar',
  },
  {
    slug: 'analisis-de-valor',
    name: 'Análisis de valor y precio',
    eyebrow: 'Propietarios y compradores',
    role: 'propietario',
    summary: 'Rango de precio por m² con propiedades comparables de la zona, para fijar un precio de salida o evaluar una oferta con criterio.',
    lead: 'Un precio fuera de mercado alarga la venta y debilita la negociación. El análisis de valor compara su propiedad con inventario real de la misma zona y tipo, y le indica dónde se ubica.',
    includes: [
      'Rango por m² (o vara² en terrenos) con comparables de la zona',
      'Ubicación de su precio: por debajo, dentro o por encima del rango',
      'Lectura de los factores que justifican una diferencia de precio',
      'Recomendación de precio de salida y de margen de negociación',
    ],
    forWho: ['Propietarios antes de publicar', 'Compradores que evalúan una oferta concreta', 'Inversionistas que comparan zonas'],
    steps: [
      ['Cree su cuenta', 'Así guardamos el análisis y le escribimos con el resultado.'],
      ['Comparta la propiedad', 'Zona, tipo, áreas y precio de referencia.'],
      ['Reciba la lectura', 'Rango, posición del precio y recomendaciones.'],
    ],
    note: 'Es una referencia de mercado y no sustituye un avalúo bancario o pericial.',
    action: 'Solicitar análisis de valor',
  },
  {
    slug: 'busqueda-asistida',
    name: 'Búsqueda asistida para compradores',
    eyebrow: 'Compradores e inversionistas',
    role: 'comprador',
    summary: 'Le avisamos cuando entra una propiedad revisada que coincide con su zona, presupuesto y tipo, y le ayudamos a evaluarla.',
    lead: 'Buscar propiedad toma tiempo y la información de los portales suele ser incompleta. Con la búsqueda asistida usted define el perfil una vez y recibe solo opciones revisadas, con su lectura de valor.',
    includes: [
      'Perfil de búsqueda por zona, tipo, presupuesto y uso (vivir o invertir)',
      'Aviso por WhatsApp cuando entra una propiedad que coincide',
      'Lectura de valor de cada opción antes de visitarla',
      'Coordinación de visitas con el asesor o propietario',
    ],
    forWho: ['Familias que buscan vivienda', 'Inversionistas en renta o plusvalía', 'Compradores que viven fuera de la ciudad'],
    steps: [
      ['Cree su cuenta', 'Es gratuita y le da acceso al inventario completo.'],
      ['Defina su búsqueda', 'Zona, presupuesto, tipo y para qué la necesita.'],
      ['Reciba opciones', 'Solo propiedades revisadas que encajan con su perfil.'],
    ],
    action: 'Activar mi búsqueda',
  },
  {
    slug: 'planes-para-inmobiliarias',
    name: 'Planes para inmobiliarias y asesores',
    eyebrow: 'Inmobiliarias y asesores',
    role: 'asesor',
    summary: 'Tarifa mensual fija para publicar su inventario con criterio, sin comisión sobre la operación y sin permanencia.',
    lead: 'Su inventario compite con cientos de anuncios genéricos. Con un plan de inmuhub cada propiedad se presenta con lectura de valor y ficha profesional, y las consultas llegan identificadas con la propiedad.',
    includes: [
      'Perfil verificado de su agencia o marca personal',
      'Publicación de inventario con lectura de valor',
      'Panel con estado y consultas por propiedad',
      'Sin comisión sobre la venta o renta, sin permanencia mínima',
    ],
    forWho: ['Asesores independientes', 'Inmobiliarias con inventario propio', 'Equipos comerciales que buscan orden'],
    steps: [
      ['Cree su cuenta de asesor', 'La revisamos antes de activarla.'],
      ['Elija su plan', 'Según el tamaño de su inventario.'],
      ['Publique y mida', 'Vea el estado y las consultas de cada propiedad.'],
    ],
    action: 'Solicitar un plan',
    related: ['/planes', 'Ver planes y tarifas'],
  },
  {
    slug: 'red-de-asesores',
    name: 'Red de asesores',
    eyebrow: 'Colaboración entre colegas',
    role: 'asesor',
    summary: 'Fichas para compartir entre colegas, sin formulario ni WhatsApp del portal, para colaborar en operaciones con orden y respeto al cliente.',
    lead: 'La colaboración entre asesores cierra operaciones que un solo asesor no alcanza. La red de inmuhub le da enlaces profesionales para compartir inventario con colegas, sin exponer al cliente ni mezclar contactos.',
    includes: [
      'Enlace corto por propiedad en red.inmuhub.com',
      'Ficha completa sin formulario ni botones de contacto',
      'Fuera de Google: solo la ve quien recibe el enlace',
      'Opción de inventario solo para colegas, fuera del catálogo público',
    ],
    forWho: ['Asesores que comparten inventario', 'Inmobiliarias que trabajan en alianza'],
    steps: [
      ['Cree su cuenta de asesor', 'La red es exclusiva para asesores verificados.'],
      ['Publique o identifique la propiedad', 'Cada ficha recibe su enlace de red.'],
      ['Comparta con colegas', 'Un enlace limpio por WhatsApp, listo para presentar.'],
    ],
    action: 'Unirme a la red',
  },
  {
    slug: 'proyectos-para-desarrolladoras',
    name: 'Proyectos nuevos para desarrolladoras',
    eyebrow: 'Desarrolladoras',
    role: 'asesor',
    summary: 'Ficha de proyecto con tipologías, precio por m² comparable con otros proyectos de la zona y reporte mensual de interés.',
    lead: 'El comprador de obra nueva compara proyectos antes de visitar una sala de ventas. inmuhub presenta su proyecto junto a sus comparables, con datos claros, y le entrega cada mes un reporte de visitas y consultas.',
    includes: [
      'Ficha de proyecto con tipologías, avance y amenidades',
      'Precio por m² frente a proyectos de la misma zona',
      'Presencia en el comparador de proyectos',
      'Reporte mensual de visitas y consultas',
    ],
    forWho: ['Desarrolladoras en preventa o construcción', 'Equipos de venta de proyectos'],
    steps: [
      ['Cree su cuenta', 'Con los datos de contacto del equipo comercial.'],
      ['Comparta el proyecto', 'Tipologías, precios, avance y material visual.'],
      ['Publicación y reporte', 'El proyecto entra al comparador y recibe su reporte mensual.'],
    ],
    action: 'Presentar mi proyecto',
    related: ['/desarrolladoras', 'Ver planes para desarrolladoras'],
  },
  {
    slug: 'tours-360',
    name: 'Tours virtuales 360°',
    eyebrow: 'Producción',
    role: 'propietario',
    summary: 'Recorrido virtual integrado en la ficha para que el comprador conozca la propiedad antes de visitarla.',
    lead: 'Un recorrido 360° filtra visitas: quien agenda ya conoce la distribución y llega con interés real. Lo producimos con cámara profesional y lo integramos en la ficha de inmuhub.',
    includes: [
      'Captura con cámara 360° profesional',
      'Recorrido navegable integrado en la ficha',
      'Paquetes Básico, Pro y Premium según el tamaño de la propiedad',
      'Enlace del tour para usar en redes y anuncios',
    ],
    forWho: ['Propiedades de alto valor', 'Compradores en el extranjero', 'Asesores que quieren menos visitas improductivas'],
    steps: [
      ['Cree su cuenta', 'Para coordinar fecha y paquete.'],
      ['Visita de captura', 'Recorrido de la propiedad con cámara 360°.'],
      ['Entrega', 'Tour integrado en la ficha y enlace para compartir.'],
    ],
    action: 'Cotizar tour 360°',
  },
  {
    slug: 'fotografia-y-video',
    name: 'Fotografía y video inmobiliario',
    eyebrow: 'Producción',
    role: 'propietario',
    summary: 'Fotografías editadas y un reel vertical que presentan la propiedad con luz, orden y criterio visual.',
    lead: 'La primera impresión de una propiedad es su fotografía principal. Producimos imágenes con iluminación cuidada y edición profesional, y un reel vertical listo para redes y anuncios.',
    includes: [
      'Sesión fotográfica con edición de luz y color',
      'Selección de la secuencia ideal para la ficha',
      'Reel vertical para Instagram, Facebook y anuncios',
      'Entrega optimizada para web y redes',
    ],
    forWho: ['Propietarios que quieren destacar su propiedad', 'Asesores que cuidan su marca'],
    steps: [
      ['Cree su cuenta', 'Para coordinar la sesión.'],
      ['Sesión en la propiedad', 'Fotografía y tomas de video en el mejor horario de luz.'],
      ['Entrega editada', 'Fotos y reel listos para publicar.'],
    ],
    action: 'Cotizar fotografía y video',
  },
  {
    slug: 'campanas-digitales',
    name: 'Campañas digitales en Meta',
    eyebrow: 'Marketing',
    role: 'asesor',
    summary: 'Estrategia, creativos y gestión de pauta en Facebook e Instagram para generar consultas calificadas.',
    lead: 'Más alcance no significa más ventas. Diseñamos campañas para el comprador correcto, con creativos de nivel y segmentación pensada para el mercado de Guatemala, y medimos el costo por consulta.',
    includes: [
      'Estrategia por propiedad, proyecto o marca',
      'Creativos: imágenes, reels y textos',
      'Segmentación y formularios para consultas calificadas',
      'Reporte de resultados y optimización mensual',
    ],
    forWho: ['Asesores e inmobiliarias', 'Desarrolladoras', 'Propietarios con propiedades de alto valor'],
    steps: [
      ['Cree su cuenta', 'Para revisar su objetivo y presupuesto.'],
      ['Diagnóstico y propuesta', 'Público, creativos y plan de inversión.'],
      ['Campaña y reporte', 'Gestión de pauta y reporte mensual de resultados.'],
    ],
    action: 'Solicitar campaña',
  },
  {
    slug: 'datos-de-mercado',
    name: 'Datos e inteligencia de mercado',
    eyebrow: 'Información',
    role: 'comprador',
    summary: 'Precio por m² por zona con anuncios reales, actualizado cada mes, para comprar, vender o invertir con criterio.',
    lead: 'Las decisiones inmobiliarias se toman con datos. inmuhub publica cada mes el precio por m² de las zonas principales de Guatemala y prepara informes a la medida para inversionistas y desarrolladoras.',
    includes: [
      'Mediana y rango por m² en Zona 10, 14, 15, 16, Cayalá, Fraijanes y Carretera a El Salvador',
      'Comparativo entre zonas y rendimiento bruto de renta',
      'Actualización mensual con anuncios reales',
      'Informes a la medida para inversión o desarrollo',
    ],
    forWho: ['Inversionistas', 'Desarrolladoras', 'Compradores que comparan zonas'],
    steps: [
      ['Cree su cuenta', 'Para recibir la actualización mensual.'],
      ['Consulte el panorama', 'Datos por zona y comparativo.'],
      ['Solicite un informe', 'Análisis a la medida de su decisión.'],
    ],
    action: 'Solicitar informe de mercado',
    related: ['/mercado', 'Ver precio por m² por zona'],
  },
];

export const serviceBySlug = (slug) => SERVICES.find((s) => s.slug === slug) || null;
